// Generated by CoffeeScript 1.6.3
var Browser, assert, browser;

Browser = require("zombie");

assert = require("assert");

browser = new Browser();

browser.visit("http://twitter.com/", function() {
  browser.wait();
  return console.log("test: ", browser.text("H1"));
});
